### ISSUE TITLE
Transforming

### ISSUE THREAD

**Issue by monicafar147** [mikael-daniels/team11_pipeline#15]
@CourtneyGallant  you can work on this file
https://github.com/mikael-daniels/team11_pipeline/blob/Transforming/Transforming.ipynb

- [x] extract hashtags

- [x] extarct municipalities

- [x] fill in the .NaN values where needed.

**Comment by monicafar147** [comment]
- [ ] extract hashtags

- [ ] extarct municipalities

- [ ] fill in the .NaN values where needed.

**Comment by monicafar147** [comment]
@CourtneyGallant if you are struggling with our code, I can suggest the following code to help you, ive been using it in our loading.ipynb and it is working.
 `def extract_municipality_hashtags(df):
    
    ''' Return a dataframe with hashtags and municipalities extracted, using dataframe obtained from Function 1

        Args: 'df', Dataframe created by Function 1

        Returns: Original dataframe, 'df', with two new columns, 'hashtags' and 'municipality'
    '''
    mun_dict = {'@CityofCTAlerts' : 'Cape Town',
                '@CityPowerJhb' : 'Johannesburg',
                '@eThekwiniM' : 'eThekwini' ,
                '@EMMInfo' : 'Ekurhuleni',
                '@centlecutility' : 'Mangaung',
                '@NMBmunicipality' : 'Nelson Mandela Bay',
                '@CityTshwane' : 'Tshwane'}

 
    l = 0
    for tweet in df['Tweets']:
      tweet = tweet.split(' ')
      for key in mun_dict.keys():
        if key in tweet:
          df.loc[l, 'municipality'] = mun_dict[key]       
      l += 1

    # Create 'hashtags' column: Mikael
    df['hashtags'] = df['Tweets'].str.lower().str.split()

    # Extract hashtags from Tweets: Monica
    hashtagslist = []
    i = 0
    for tweet in df['hashtags']:
      hashtags = []
      for word in tweet:
        if word.startswith('#'):
          hashtags.append(word)
      hashtagslist.append(hashtags)
      i += 1
    
    df['hashtags'] = hashtagslist
    # Fill empty values in 'hashtags' columns with np.nan: Courtney

    return df`

**Comment by CourtneyGallant** [comment]
Thank you Monica.
